### ISSUE TITLE
???

### ISSUE THREAD

**Issue by WhiteHodok** [slenderik/myomsk#1]
- Почему бренча всего 1 ?
- Почему пейджа в actions загружена, но недоступна?

**Comment by slenderik** [comment]
Бранчи использовать не умею.

Пейдж не работает из-за того что я закрывал репозиторий, ТК надо было временно хранить пароль в коде. (Абсолютно неприемлемо, знаю)

Этот репозиторий чисто для хранения текущей версии кода. Микро версия сайта стоит на хостинге, и доступна по домену my-omsk. Там микро версия ТК сжимали сроки, перед промежуточной сдачей.

Сейчас я отдыхаю от проекта, через неделю две стоит ждать изменения: использование генерации страниц и использовать бд в продакшне, не как сейчас.
